module-federation/vite

README.md
examples/vite/vite.config.js
src/index.ts
src/utils/normalizeBuild.ts
src/utils/normalizeModuleFederationOptions.ts

@husayt 
https://github.com/module-federation/vite/pull/29#issuecomment-2265106681

fix: Ensure @module-federation/runtime singleton

---

.github/workflows /pkg-pr-new.yml
pnpm-lock.yaml

https://blog.stackblitz.com/posts/pkg-pr-new/

feat: add pkg-pr-new GH action

---

examples/vite/src/App.jsx
package.json
pnpm-lock.yaml
src/index.ts
src/utils/normalizeModuleFederationOptions.ts
src/utils/vitePluginAddEntry.ts
src/utils/vitePluginOverrideModule.ts

* fix: #36 
* fix: dynamic import

fix: #36 and dynamic import

---

src/index.ts
src/plugins/pluginProxyRemoteEntry.ts
src/virtualModules/virtualRemoteEntry.ts

fix https://github.com/module-federation/vite/issues/42#issuecomment-2282324217

fix: windows remoteEntry error

---

examples/vite-vite/vite-host/src/App.jsx
examples/vite-vite/vite-host/vite.config.js
examples/vite-vite/vite-remote/vite.config.js

@gioboa somehow previous pR had some files mixed up. Here is the fix for hat

fix updated examples

---

examples/rust-vite/vite-remote/src/main.jsx
examples/vite-vite/vite-host/package.json
examples/vite-vite/vite-host/src/App.jsx
examples/vite-vite/vite-host/src/mfPlugins.js
examples/vite-vite/vite-host/vite.config.js
examples/vite-vite/vite-remote/package.json
examples/vite-vite/vite-remote/src/AgGridDemo.jsx
examples/vite-vite/vite-remote/src/App1.jsx
examples/vite-vite/vite-remote/src/App2.jsx
examples/vite-vite/vite-remote/src/Mui5Widget.module.css
examples/vite-vite/vite-remote/src/MuiDemo.jsx
examples/vite-vite/vite-remote/src/agGrid.css
examples/vite-vite/vite-remote/src/main.jsx
examples/vite-vite/vite-remote/vite.config.js
pnpm-lock.yaml

* added MUI examples
* used vite preview instead of http-server
* more logging
* using react 18.2 on remote and 18.3 on server to show MF in effect
*  more smaller improvements

improved  examples with MUI and etc

---

README.md
examples/vite-vite/vite-remote/src/main.jsx
examples/vite-vite/vite-remote/vite.config.js
package.json
pnpm-lock.yaml
src/index.ts
src/plugins/pluginModuleParseEnd.ts
src/plugins/pluginProxyRemoteEntry.ts
src/plugins/pluginProxyRemotes.ts
src/plugins/pluginProxySharedModule_preBuild.ts
src/utils/PromiseStore.ts
src/utils/VirtualModule.ts
src/utils/normalizeModuleFederationOptions.ts
src/utils/packageNameUtils.ts
src/virtualModules/virtualRemoteEntry.ts
src/virtualModules/virtualRemotes.ts
src/virtualModules/virtualShared_preBuild.ts

* feat: #40  
* fix: #64  
* fix: #66

feat: shared-slash

---

README.md
lib/index.cjs
lib/index.esm.js
lib/index.modern.js
lib/index.umd.js
lib/utils/getLocalSharedImportMap_windows.d.ts
lib/utils/localSharedImportMap_temp.d.ts
lib/utils/localSharedImportMap_windows.d.ts
src/utils/localSharedImportMap_temp.ts
src/virtualModules/virtualRemoteEntry.ts

fix: Partial development environment

---

package.json

chore: change postinstall script to use npm

---

src/utils/normalizeModuleFederationOptions.ts

chore: add types for dev and dts properties

---

.github/workflows/unit-test.yml
package.json
pnpm-lock.yaml
src/plugins/pluginMFManifest.ts
src/utils/__tests__/normalizeModuleFederationOption.test.ts
src/utils/normalizeModuleFederationOptions.ts
tsconfig.json
vitest.config.ts

- adds a basic vitest unit test setup including github action
- tests normalizeModuleFederationOptions

chore: add unit test setup + test normalizeModuleFederationOptions

---

src/index.ts
src/virtualModules/virtualRuntimeInitStatus.ts

fix: Increase compatibility

---

README.md

docs: add Svelte example

---

README.md

docs: add SolidJS example

---

src/utils/normalizeModuleFederationOptions.ts
src/virtualModules/virtualRemoteEntry.ts

https://github.com/module-federation/core/pull/3064

fix: solve issue during refresh

---

README.md
src/index.ts
src/plugins/pluginAddEntry.ts
src/plugins/pluginProxyRemoteEntry.ts
src/utils/__tests__/normalizeModuleFederationOption.test.ts
src/utils/normalizeModuleFederationOptions.ts
src/virtualModules/virtualRemoteEntry.ts

fix: 
#180
#179 
feat:
[implementation](https://module-federation.io/configure/implementation.html)

fix: manage implementation option + fix circular import issue

---

examples/vite-vite/vite-host/package.json
examples/vite-vite/vite-remote/package.json
pnpm-lock.yaml
src/index.ts

https://github.com/vitejs/vite/issues/18850
Fixes #201

feat: support Vite v6

---

examples/vite-vite/vite-remote/package.json
pnpm-lock.yaml
src/plugins/pluginProxySharedModule_preBuild.ts

fix: vite6.0.4

---

src/index.ts
src/utils/VirtualModule.ts

https://github.com/module-federation/vite/issues/254

fix: solve issue with location of __mf__virtual in monorepo

---

src/plugins/pluginMFManifest.ts

Reverting https://github.com/module-federation/vite/pull/262
Reason: https://github.com/module-federation/vite/pull/262#issuecomment-2689156064

revert(manifest): public path (#262)

---

src/plugins/pluginMFManifest.ts

Get original base and set 'auto' to publicPath properly.
Refs: #251 , #261

fix: publicPath with 'auto' value.

---

package.json
pnpm-lock.yaml

Updated needed for fix a issue [[Bug]: Repeated Error Prefix in Module Federation Runtime Errors](https://github.com/module-federation/vite/issues/318)

feat: updated dependency @module-federation/runtime to ^0.17.1
