src/index.ts

Reference https://github.com/module-federation/vite/issues/8#issuecomment-1620914897.
Fixed the vite module parsing error caused by the error call timing.
close: #8

Refactor federation init he110

---

src/dev-externals-mixin.ts
src/index.ts

close #14 
The problem has two parts:
1. When base is configured, the address of `remoteEntry.json` does not match. The reason is that [this line of code](https://github.com/module-federation/vite/blob/main/src/index.ts#L51) splices the address directly, but Vite's base doesn't affect the path in dist, so the urls don't match.
2. `baseUrl` is not supported when external imports are replaced [in the plugin](https://github.com/module-federation/vite/blob/main/src/dev-externals-mixin.ts#L22). The reason is that the replacement rule only matches `/@id/${libraryName}`. When `baseUrl` is configured, the import path is: `/${baseUrl}/@id/${libraryName}`. So we need to modify the rule to match the quotes directly.

Feat base url he110

---

README.md
examples/rust/rsbuild.config.ts
examples/rust/src/App.tsx
examples/vite/package.json
pnpm-lock.yaml
src/index.ts
src/utils/normalizeModuleFederationOptions.ts
src/utils/vitePluginAddEntry.ts

* export set __esModule: true
* addEntry support hash
* default requiredVersion "^"

fix: remoteEntry support hash; format dynamic es module

---

src/index.ts
src/plugins/pluginProxyRemoteEntry.ts
src/plugins/pluginProxyRemotes.ts
src/plugins/pluginProxySharedModule_preBuild.ts
src/utils/VirtualModule.ts
src/virtualModules/index.ts
src/virtualModules/virtualRemoteEntry.ts
src/virtualModules/virtualRemotes.ts
src/virtualModules/virtualShared_preBuild.ts

Fixes an extreme monorepo scenario where multiple packages share a node_modules directory and multiple `shared` configurations conflict.
In this [demo](https://github.com/module-federation/vite/issues/40#issuecomment-2317363004), there is no conflict between two shared files.

fix: monorepo

---

src/index.ts
src/plugins/pluginAddEntry.ts
src/virtualModules/index.ts
src/virtualModules/virtualRemoteEntry.ts

Some people have reported that in some scenarios, the remote virtual module will be used as the host module to initiate a request, so remove the virtual module reference in remoteEntry.js

fix: Remote virtual module path

---

src/plugins/pluginMFManifest.ts

In dev mode, additional fields can be included in the manifest.json to enhance the user experience with the Chrome plugin.​

feat: dev mode manifest.json

---

src/utils/normalizeModuleFederationOptions.ts

`shareStrategy` was implemented as optional but was required in the typing.
Ref: https://github.com/module-federation/vite/pull/105#discussion_r1786523283

fix: changed shareStrategy property to optional in ModuleFederationOptions

---

src/plugins/pluginMFManifest.ts
src/utils/normalizeModuleFederationOptions.ts

fix: #133 ; fix publicPath; feat: getPublicPath

fix: hotfix manifest

---

src/utils/localSharedImportMap_temp.ts

cjs/esm depends on package.json's type, would be better to use non ambiguous extension.

chore: use cjs extension in temporary file

---

src/utils/localSharedImportMap_temp.ts

`node_modules` is commonly used as cache folder.
Usually it's eslint and prettier ignored.
Related to https://github.com/module-federation/vite/issues/137

fix: keep cache inside node_modules by default to avoid problems with prettier and eslint

---

src/index.ts
src/plugins/pluginAddEntry.ts
src/virtualModules/virtualRemoteEntry.ts

hotfix:
If the remote is configured as `exposes: {".": "./src/main"}`, the remote will automatically call runtime.init(), which may cause intermittent errors in certain network environments.

fix: issue with multiple init calls in remote

---

src/index.ts

expose plugin option to other plugins without headache, now plugin authors can get user configuration : 
related discussion: https://github.com/rolldown/rolldown/discussions/2577#discussioncomment-11137593

feat: expose plugin options to other plugins

---

package.json
pnpm-lock.yaml

fix(deps): bump @module-federation/runtime version

---

src/plugins/pluginAddEntry.ts
src/virtualModules/virtualRemoteEntry.ts

fix: Inject hostInit as entry if there are no html entry files

---

src/plugins/pluginAddEntry.ts
src/plugins/pluginProxyRemoteEntry.ts

fix: serve on ipv4

---

src/plugins/pluginAddEntry.ts
src/plugins/pluginProxyRemoteEntry.ts

fix: App not works on custom local domain with shared dependencies

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml

docs: create default issue template

---

src/plugins/pluginMFManifest.ts

The pr fixed some issues.
- The mainifest should generate `publicPath` as key
- `getPublicPath` is not working at dev

fix(manifest): public path

---

examples/vite-webpack-rspack/host/vite.config.js
examples/vite-webpack-rspack/remote/vite.config.js
src/plugins/pluginMFManifest.ts

If filename !== remoteEntry, the metaData of manifest.json cannot get the correct name because the name of the vite bundle does not contain the suffix

fix: solve issue with filename !== remoteEntry

---

src/virtualModules/virtualRemoteEntry.ts

Without this attribute, share scope isolation does not work as every remote will fall back to the 'default' share scope.

fix: add shareScope attribute to usedRemotes in virtualRemoteEntry

---

packages/module-federation-vite/.lintstagedrc

prettier-quick looks at git for what files have changed, but lint-staged is already running in a loose file environment.  However, lint-staged passes a list of all changed files as command arguments.
As such, lint-staged should run prettier directly, as it will receive the list of changed files and restrict what it formats.

fix: use prettier directly in lint-staged

---

src/plugins/pluginProxyRemoteEntry.ts
src/utils/__tests__/normalizeModuleFederationOption.test.ts
src/utils/normalizeModuleFederationOptions.ts

I have a use case that I need to run the remote in dev mode but keep attaching it to the host.
This original line
`const origin = window ? window.origin : "//${host}:${viteConfig.server?.port}"`
prevents me from using the remote this way, because it tries to load the remote from the host url.
Adding this new parameter makes it possible to do this use case and keep the original behavior.

feat: add ignoreOrigin option

---

src/plugins/pluginMFManifest.ts

My host application uses parametrized manifest URLs (`mf-manifest.json?v=1.2.3`) for caching reasons
Current implementation fails to load manifests with query params in dev mode (returns HTML instead of JSON)
Ignore all query parameters when loading `mf-manifest.json`
✅ Versioned manifests (`?v=1.2.3`)
✅ Standard manifests (no params)
✅ Both development and production modes
Enables proper manifest loading during development

feat: support manifest's query params

---

.github/workflows/release-plugin-alpha.yml
.github/workflows/release-runtime-alpha.yml
packages/module-federation-vite/package.json

Before continuing, I would like to get a release of the runtime as-is under an alpha tag to check that everything works.
After this, I still need to investigate how to allow the main vite plugin to consume the new runtime from the workspace for local development while consuming the npm package when published.  That seems to be what [pnpm deploy](https://pnpm.io/cli/deploy) is for.
For now, publishing the actual plugin as alpha-2 has no actual changes yet, and probably unnecessary, but I do want to get the runtime published to npm.  Once it's up, I will test it with the `implementation` property to make sure everything works.

feat: Alpha release workflows

---

src/utils/normalizeModuleFederationOptions.ts

Fixes #288 
@gioboa I hope this fix is good. I have no clue how it's supposed to work. I also did not test this change yet, but I think it should work logically wise.

fix: getting share item when package is only partially shared (fixes #288)

---

package.json
pnpm-lock.yaml

Updating to latest `@module-federation/runtime` version.
In my project I use both `@module-federation/vite` and `@module-federation/enhanced`, this old version on runtime is preventing me to update versions due to ts-comp errors.

chore: Update @module-federation/runtime to ^0.16.0

---

src/utils/VirtualModule.ts
src/utils/__tests__/VirtualModule.test.ts

Fixes an issue where `VirtualModule` failed to detect the correct suffix for scoped packages that contain dots in the namespace (e.g., `@company.x.y/lib.name`).
This caused the suffix to be incorrectly split from the namespace, resulting in broken imports.
Fixes: https://github.com/module-federation/vite/issues/321

fix: correctly detect suffix for scoped packages with dots

---

src/plugins/pluginDevProxyModuleTopLevelAwait.ts

I ran into an edge case recently during some experimentation.
If you try running multiple module federation plugin instances in 1 vite config, the top await rewriter plugin will try to process itself multiple times. Around the 3rd time it created a duplicate const and the AST parse failed.
This is a simple fix that prevents that edge case.
This is part of a series of PR's to upstream my R&D.

fix: prevent multiple processing of await plugin output
